config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes do
    post 'made_history', to: 'made_histories#create'
  end
  resources :tags
  resources :tag_categories
  get 'ranking_pages/rank'

end

app/models/made_history.rb
class MadeHistory < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :tag_recipe_relations
  has_many :tags, through: :tag_recipe_relations
  has_many :made_histories

  validates :name, length: { maximum: 100 }, presence: true
  validates :material, length: { maximum: 50 }, presence: true
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :tag_category
  has_many :tag_recipe_relations
  has_many :recipes, through: :tag_recipe_relations

  validates :name, length: { maximum: 50 }, presence: true
end

app/models/tag_category.rb
class TagCategory < ActiveRecord::Base
  has_many :tags

  validates :name, length: { maximum: 50 }, presence: true
end

app/models/tag_recipe_relation.rb
class TagRecipeRelation < ActiveRecord::Base
  belongs_to :tag
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/made_histories_controller.rb
class MadeHistoriesController < ApplicationController
  before_action :set_recipe

  def create
    if MadeHistory.create(recipe_id: @recipe.id)
      redirect_to @recipe, notice: 'MadeHistory was successfully created.'
    else
      render :new
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/ranking_pages_controller.rb
class RankingPagesController < ApplicationController
  def rank
    @recipes = Recipe.order('created_at ASC')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @tag = Tag.find(@recipe.tag_ids)
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully destroy.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :material, :url, :content, :memo, { :tag_ids => [] })
  end
end

app/controllers/tag_categories_controller.rb
class TagCategoriesController < ApplicationController
  before_action :set_tag_category, only: [:show, :edit, :update, :destroy]
  def index
    @tag_categories = TagCategory.all
  end

  def show
  end

  def new
    @tag_category = TagCategory.new
  end

  def edit
  end

  def create
    @tag_category = TagCategory.new(tag_category_params)

    if @tag_category.save
      redirect_to tag_categories_path, notice: 'TagCategory was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tag_category.update(tag_category_params)
      redirect_to tag_categories_path, notice: 'TagCategory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tag_category.destroy
    redirect_to tag_categories_url, notice: 'TagCategories was successfully'
  end

  private

  def set_tag_category
    @tag_category = TagCategory.find(params[:id])
  end

  def tag_category_params
    params.require(:tag_category).permit(:name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tags, only: [:show, :edit, :update, :destroy] 

  def index
    @tags = Tag.all
  end

  def show
    @recipe = Recipe.find(@tag.recipe_ids)
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: 'Tag was successfully destroy'
  end

  private

  def set_tags
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :tag_category_id, { :recipe_ids => [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tag_categories_helper.rb
module TagCategoriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookKoko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ranking_pages/_form.html.erb
<%= form_tag('/ranking_pages/rank') do %>
  <%= select_tag 'rank[rank_order]', options_for_select([
    ["レシピ名(昇順)", "recipe_name_ASC"],
    ["レシピ名(降順)", "recipe_name_DESC"],
    ["前回作った日(昇順)", "last_cook_ASC"],
    ["前回作った日(降順)", "last_cook_DESC"],
    ["作った回数(昇順)", "made_count_ASC"],
    ["作った回数(降順)", "made_count_DESC"]]),
    :prompt => "選択してください" %>
<% end %>

app/views/ranking_pages/rank.html.erb
<h1>Recipe ranking</h1>

<%= render 'form' %>

<ol type="1">
<% @recipes.each do |recipe| %>
  <li>
    <%= recipe.name %>
    <%= recipe.created_at %>
  </li>
  <br>
<% end %>
</ol>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

<dl>
  <dt><%= f.label :name, "レシピ名" %></dt>
  <dd><%= f.text_field :name, class: 'form-control' %></dd>

  <dt><%= f.label :material, "材料" %></dt>
  <dd><%= f.text_field :material, class: 'form-control' %></dd>

  <dt><%= f.label :url, "参考URL" %></dt>
  <dd><%= f.text_field :url, class: 'form-control' %></dd>

  <dt><%= f.label :content, "作り方" %></dt>
  <dd><%= f.text_area :content, class: 'form-control' %></dd>

  <dt><%= f.label :memo, "一言メモ" %></dt>
  <dd><%= f.text_area :memo, class: 'form-control' %></dd>

  <dt><%= f.label :tags %></dt>
  <dd>
    <%= collection_check_boxes(:recipe, :tag_ids, Tag.all, :id, :name ) do |tag| %>
      <% tag.label { tag.check_box + tag.text } %>
    <% end %>
  </dd>
</dl>

<%= f.submit "登録する", class: 'btn, btn-primary' %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Recipe edit</h1>

<%= render 'form' %>

<%= link_to 'Show', recipe_path %>
<%= link_to 'Index', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipe index</h1>

<table>
  <tr>
    <th>レシピ名</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.name %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, data: { :confirm => 'Are you sure?' }, :method => :delete %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'New', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>Recipe new</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1>Recipe show</h1>

<h2><%= @recipe.name %></h2>
<br>

<h3>作った回数</h3>
<div><%= MadeHistory.where(recipe_id: @recipe.id).count %>回</div>
<%= form_tag recipe_made_history_path(@recipe) do %>
  <%= submit_tag "作ったよボタン", class: 'btn btn-primary' %>
<% end %>

<h3>参考URL</h3>
<div><%= @recipe.url %></div>
<br>

<h3>材料</h3>
  <dl>
    <dt><%= @recipe.material %></dt><dd>???ml</dd>
  </dl>
<br>

<h3>作り方</h3>
<div><%= @recipe.content %></div>
<br>

<h3>一言メモ</h3>
<div><%= @recipe.memo %></div>
<br>

<h3>関連タグ</h3>
<div>
  <% @tag.each do |tag| %>
    <%= tag.name %>
  <% end %>
</div>
<br>

<%= link_to 'Back', recipes_path %>
<%= link_to 'Edit', edit_recipe_path %>
<%= link_to 'Destroy', recipe_path, data: { :confirm => 'Are you sure?' }, :method => :delete %>

app/views/tag_categories/_form.html.erb
<%= form_for @tag_category do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit "登録する", class: 'btn btn-primary' %>
<% end %>

app/views/tag_categories/edit.html.erb
<h1>TagCategory edit</h1>

<%= render 'form' %>

<%= link_to 'Show', tag_category_path %>
<%= link_to 'Index', tag_categories_path %>

app/views/tag_categories/index.html.erb
<h1>TagCategory index</h1>

<table>
  <tr>
    <th>カテゴリ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @tag_categories.each do |tag_category| %>
    <tr>
      <td><%= tag_category.name %></td>
      <td><%= link_to 'Show', tag_category %></td>
      <td><%= link_to 'Edit', edit_tag_category_path(tag_category) %></td>
      <td><%= link_to 'Destroy', tag_category, data: { :confirm => 'Are you sure?' }, :method => :delete %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New', new_tag_category_path %>

app/views/tag_categories/new.html.erb
<h1>TagCategory new</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_categories_path %>

app/views/tag_categories/show.html.erb
<h1>TagCategory show</h1>

<table>
  <tr>
    <th>カテゴリ</th>
    <th>タグ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= @tag_category.name %></td>
    <td>
      <% @tag_category.tags.each do |tag| %>
        <%= tag.try(:name) %>
      <% end %>
    </td>
    <td><%= link_to 'Back', tag_categories_path  %></td>
    <td><%= link_to 'Edit', edit_tag_category_path  %></td>
    <td><%= link_to 'Destroy', tag_category_path, data: { :confirm => 'Are you sure?' }, :method => :delete %></td>
  </tr>
</table>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <%= f.label :name, "タグ名" %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>

  <%= f.label :tag_category_id, "カテゴリ" %>
  <%= f.select :tag_category_id, TagCategory.all.map{
    |tag_category| [tag_category.name, tag_category.id]
  } %>
  <br>

  <%= f.label :recipes %>
  <%= collection_check_boxes(:tag, :recipe_ids, Recipe.all, :id, :name ) do |recipe| %>
    <% recipe.label { recipe.check_box + recipe.text } %>
  <% end %>
  <br>

  <%= f.submit "登録する", class: 'btn btn-primary' %>
<% end %>

app/views/tags/edit.html.erb
<h1>Tag edit</h1>

<%= render 'form' %>

<%= link_to 'Show', tag_path %>
<%= link_to 'Index', tags_path %>

app/views/tags/index.html.erb
<h1>Tag index</h1>

<table>
  <tr>
    <th>タグ名</th>
    <th>カテゴリ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= tag.tag_category.try(:name) %></td>
      <td><%= link_to 'Show', tag %></td>
      <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
      <td><%= link_to 'Destroy', tag, data: { :confirm => 'Are you sure?' }, :method => :delete %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New', new_tag_path %>

app/views/tags/new.html.erb
<h1>Tag new</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<h1>Tag show</h1>

<table>
  <tr>
    <th>タグ名</th>
    <th>カテゴリ</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= @tag.name %></td>
    <td><%= @tag.tag_category.try(:name) %></td>
    <td>
      <% @recipe.each do |recipe| %>
        <%= recipe.name %>
      <% end %>
    </td>
    <td><%= link_to 'Back', tags_path %></td>
    <td><%= link_to 'Edit', edit_tag_path %></td>
    <td><%= link_to 'Destroy', tag_path, data: { :confirm => 'Are you sure?' }, :method => :delete %></td>
  </tr>
</table>